//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GravityJavaTest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1175256991")]
        public string OID {
            get {
                return ((string)(this["OID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.emergepay-sandbox.chargeitpro.com/virtualterminal/v1")]
        public string endpointURL {
            get {
                return ((string)(this["endpointURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://assets.emergepay-sandbox.chargeitpro.com//cip-hosted-fields.js")]
        public string assetsCheckoutURL {
            get {
                return ((string)(this["assetsCheckoutURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aWQiOjkzMywib2lkIjoxMTc1MjU2OTkxLCJ0b2tl" +
            "bl91c2UiOiJvcnQiLCJybmQiOjE5OTMxMTM2NTAuOTE1NTE1LCJncm91cHMiOlsiT3JnQVBJVXNlcnMi" +
            "XSwiaWF0IjoxNjgwODk2MDczfQ.wiscESppOHcEjDjkzByJF6qtgVLHIdGILTewnPo44pk")]
        public string startTransactionToken {
            get {
                return ((string)(this["startTransactionToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(none)")]
        public string processTransactionToken {
            get {
                return ((string)(this["processTransactionToken"]));
            }
        }
    }
}
